# Generated by Django 5.1.4 on 2026-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('roads', 'Roads'), ('sanitation', 'Sanitation'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('portal', 'Portal'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('cluster_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
