# Generated by Django 5.1.4 on 2026-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='impact_score',
            field=models.IntegerField(default=0),
        ),
    ]
