# Generated by Django 5.1.4 on 2026-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_impact_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='source',
            field=models.CharField(choices=[('portal', 'Portal'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
