# Generated by Django 5.1.4 on 2026-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='source',
            field=models.CharField(choices=[('portal', 'Portal'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
