# Generated by Django 5.1.4 on 2026-04-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='affected_population_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='duration_hint',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='risk_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.department'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('city', 'City'), ('village', 'Village')], default='city', max_length=20)),
            ],
            options={
                'ordering': ['city', 'area'],
                'unique_together': {('city', 'area')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.location'),
        ),
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.location')),
            ],
            options={
                'unique_together': {('department', 'location')},
            },
        ),
    ]
