# Generated by Django 5.1.4 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_department_complaint_affected_population_estimate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("username", models.CharField(max_length=60, unique=True)),
                ("password", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("current_load", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="complaints.department"),
                ),
                (
                    "location_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="complaints.location",
                    ),
                ),
            ],
            options={"ordering": ["department__name", "current_load", "name"]},
        ),
        migrations.CreateModel(
            name="ResolutionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("resolved_pending_verification", "Resolved Pending Verification"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="assigned",
                        max_length=40,
                    ),
                ),
                ("sla_due_at", models.DateTimeField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("ttr_minutes", models.IntegerField(default=0)),
                ("escalated_count", models.IntegerField(default=0)),
                ("last_escalated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not Requested"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_requested",
                        max_length=20,
                    ),
                ),
                ("verification_requested_at", models.DateTimeField(blank=True, null=True)),
                ("verification_photo_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_task",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="complaints.officer",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
