# Generated by Django 6.0.4 on 2026-04-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_officer_resolutiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officer',
            name='max_active_tasks',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='resolutiontask',
            name='escalated_to_manager_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutiontask',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tasks', to='complaints.officer'),
        ),
        migrations.AlterField(
            model_name='resolutiontask',
            name='state',
            field=models.CharField(choices=[('queued', 'Queued'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved_pending_verification', 'Resolved Pending Verification'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='assigned', max_length=40),
        ),
    ]
